name: Publish to Central Maven Repo


on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v2

    - name: Configure java
      uses: actions/setup-java@v1
      with:
        java-version: 11
        server-id: github # Va  lue of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Retrieve Credentials for Publishing Maven package
      uses: action-factory/aws-secrets-manager-action@v0.4.0
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws_region: us-west-2
        secrets: |
          revai-java-sdk/sonatype-account/username
          revai-java-sdk/sonatype-account/password
          revai-java-sdk/maven-pgp-signing/passphrase
          revai-java-sdk/maven-pgp-signing/private-key
        parse_json: false
          
    - name: Release Maven package
      uses: samuelmeuli/action-maven-publish@v1
      with:
        gpg_private_key: ${{ secrets.REVAI_JAVA_SDK_MAVEN_PGP_SIGNING_PRIVATE_KEY }}
        gpg_passphrase: ${{ secrets.REVAI_JAVA_SDK_MAVEN_PGP_SIGNING_PASSPHRASE }}
        nexus_username: ${{ secrets.REVAI_JAVA_SDK_SONATYPE_ACCOUNT_USERNAME }}
        nexus_password: ${{ secrets.REVAI_JAVA_SDK_SONATYPE_ACCOUNT_PASSWORD }}
        maven_profiles: "release"
      env:
        REVAI_ACCESS_TOKEN: ${{ secrets.INTEGRATION_TEST_ACCESS_TOKEN }}
  
    - name: Notify slack fail
      if: failure()
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      uses: voxmedia/github-action-slack-notify-build@v1
      with:
        channel: revai-alerts-prod
        status: FAILED
        color: danger
  
    - name: Notify slack success
      if: success() 
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      uses: voxmedia/github-action-slack-notify-build@v1
      with:
        channel: revai-alerts-prod
        status: SUCCESS
        color: good
